In [54]:
import torch
import numpy as np

In [4]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [8]:
shape = (2,3)
rand_tensor = torch.rand(shape)
print(rand_tensor)
ones_tensor = torch.ones(shape)
print(ones_tensor)
zeors_tensor = torch.zeros(shape)
print(zeors_tensor)

tensor([[0.6212, 0.9585, 0.0607],
        [0.5718, 0.6522, 0.1558]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tensor = torch.rand(3,4)
tensor.shape

torch.Size([3, 4])

In [11]:
tensor.device

device(type='cpu')

In [12]:
tensor.dtype

torch.float32

In [14]:
torch.cuda.is_available()

False

In [16]:
tensor = torch.randint(0,3,(4,4))
print(tensor)
print(tensor[0])
print(tensor[:, 0])


tensor([[2, 0, 0, 0],
        [1, 2, 2, 0],
        [0, 0, 2, 0],
        [1, 0, 2, 2]])
tensor([2, 0, 0, 0])
<built-in method item of Tensor object at 0x000001E834C38BD0>


In [21]:
t1  = torch.cat([tensor, tensor, tensor], dim = 1 )
print(t1)

tensor([[2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0],
        [1, 2, 2, 0, 1, 2, 2, 0, 1, 2, 2, 0],
        [0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0],
        [1, 0, 2, 2, 1, 0, 2, 2, 1, 0, 2, 2]])


In [23]:
tensor = torch.ones(3,2)+2

In [24]:
tensor @ tensor.T

tensor([[18., 18., 18.],
        [18., 18., 18.],
        [18., 18., 18.]])

In [26]:
y3 = torch.rand_like(tensor)
print(y3)

tensor([[0.3531, 0.4553],
        [0.7100, 0.1220],
        [0.2658, 0.9520]])


In [30]:
torch.matmul(tensor, tensor.T, out = y3)
print(y3)

tensor([[18., 18., 18.],
        [18., 18., 18.],
        [18., 18., 18.]])


In [31]:
z1 = tensor * tensor
print(z1)

tensor([[9., 9.],
        [9., 9.],
        [9., 9.]])


In [32]:
z2 = tensor.mul(tensor)
print(z2)

tensor([[9., 9.],
        [9., 9.],
        [9., 9.]])


In [33]:
z3 = torch.rand_like(tensor)
print(z3)

tensor([[0.2949, 0.2184],
        [0.4246, 0.1506],
        [0.7866, 0.6864]])


In [34]:
torch.mul(tensor, tensor, out = z3)
print(z3)

tensor([[9., 9.],
        [9., 9.],
        [9., 9.]])


In [37]:
agg = tensor.sum().item()
print(agg)

18.0


In [38]:
tensor.add_(5)
print(tensor)

tensor([[8., 8.],
        [8., 8.],
        [8., 8.]])


In [41]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
t.add_(2)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [57]:
#실습1-1
tensor1 = [[1,2],[3,4]]
tensor2 = [[5,6],[7,8]]
np_array1 = np.array(tensor1)
np_array2 = np.array(tensor2)

tensor1 = torch.from_numpy(np_array1)
tensor2 = torch.from_numpy(np_array2)
z1 = tensor1 @ tensor2
print(z1)

#실습1-2
print(z1.sum().item())

#실습1-3
torch.mul(tensor1, tensor2, out = z2)
print(z2)

tensor([[19, 22],
        [43, 50]], dtype=torch.int32)
134
tensor([[ 5., 12.],
        [21., 32.]])


In [61]:
x = torch.ones(2,2, requires_grad=True)
y1 = x + 2
print(y1)

None


c:\Users\ppjj2\anaconda3\lib\site-packages\torch\_tensor.py:1083: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\b\abs_bao0hdcrdh\croot\pytorch_1675190257512\work\build\aten\src\ATen/core/TensorBody.h:482.)
  return self._grad


In [62]:
x = torch.tensor(2.0, requires_grad = True)
y = 3*x**2 + 4*x + 1
y.backward()
print(x.grad)
print(y)

tensor(16.)
tensor(21., grad_fn=<AddBackward0>)


In [64]:
x = torch.tensor(1.0, requires_grad = True)
z = torch.tensor(2.0, requires_grad = True)

y = x**3 + z**2
y.backward()
print(x.grad, z.grad)
print(y)

tensor(3.) tensor(4.)
tensor(5., grad_fn=<AddBackward0>)


In [68]:
import torch
import torch.nn as nn #뉴럴 네트워크, 신경망을 구성하는데 필요한 모든 구성 요소를 제공
import torch.nn.functional as F # convolution function, pooling function, activation function, dropout function, loss function 등의 기능 제공
import torch.optim as optim #optimizer 제공

w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

X = torch.FloatTensor([[ 1.76405235,  0.40015721],
 [ 0.3130677,  -0.85409574],
 [ 1.86755799, -0.97727788],
 [ 0.95008842, -0.15135721],
 [ 0.14404357,  1.45427351],
 [ 0.76103773,  0.12167502],
 [ 0.44386323,  0.33367433],
 [ 0.97873798,  2.2408932 ],
 [ 1.49407907, -0.20515826],
 [-0.10321885,  0.4105985 ]])

y = torch.FloatTensor([ 63.53688815, -71.72648252, -61.68390971,   1.57941977, 140.99124416,
  25.4497451,   40.69691806, 229.37436452,   6.57023041,  42.57804267])

X1 = X[:,0]
print(X1)
X2 = X[:,1]
print(X2)


optimizer = optim.SGD([w1,w2, b], lr=1e-3)


nb_epochs = 100000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = X1*w1 + X2*w2 + b

    # cost 계산
    cost = torch.mean((hypothesis - y) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() # 미분한 값들은 누적되는 특징이 있기 때문에 0으로 초기화
    cost.backward() # 역전파
    optimizer.step() # 역전파시에 계산된 값으로 매개변수 수정

    # 100번마다 로그 출력
    if epoch % 10000 ==0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(),w1.item(), b.item(), cost.item()
        ))

tensor([ 1.7641,  0.3131,  1.8676,  0.9501,  0.1440,  0.7610,  0.4439,  0.9787,
         1.4941, -0.1032])
tensor([ 0.4002, -0.8541, -0.9773, -0.1514,  1.4543,  0.1217,  0.3337,  2.2409,
        -0.2052,  0.4106])
Epoch    0/100000 w1: 0.053 w2: 0.053 b: 0.083 Cost: 8964.013672
Epoch 10000/100000 w1: 13.134 w2: 13.134 b: 4.511 Cost: 1.660413
Epoch 20000/100000 w1: 13.544 w2: 13.544 b: 4.034 Cost: 1.580720
Epoch 30000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 40000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 50000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 60000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 70000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 80000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 90000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
Epoch 100000/100000 w1: 13.554 w2: 13.554 b: 4.022 Cost: 1.580665
